$data = [System.IO.File]::ReadAllText("c:\Users\ntkha\Documents\friends furnitures\src\data\furnitureData.js", [System.Text.Encoding]::UTF8)
$app = [System.IO.File]::ReadAllText("c:\Users\ntkha\Documents\friends furnitures\app.js", [System.Text.Encoding]::UTF8)
$css = [System.IO.File]::ReadAllText("c:\Users\ntkha\Documents\friends furnitures\styles.css", [System.Text.Encoding]::UTF8)

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("<!DOCTYPE html>")
[void]$sb.AppendLine("<html lang=""en"">")
[void]$sb.AppendLine("<head>")
[void]$sb.AppendLine("  <meta charset=""UTF-8"" />")
[void]$sb.AppendLine("  <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"" />")
[void]$sb.AppendLine("  <title>FRIENDS FURNITURE | Where Luxury Meets Comfort</title>")
[void]$sb.AppendLine("  <meta name=""description"" content=""Ultra-Premium Multi-Role Royal Smart Furniture Platform & Supply Chain Management."" />")
[void]$sb.AppendLine("  <link rel=""icon"" href=""data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>👑</text></svg>"">")
[void]$sb.AppendLine("  <link rel=""preconnect"" href=""https://fonts.googleapis.com"" />")
[void]$sb.AppendLine("  <link rel=""preconnect"" href=""https://fonts.gstatic.com"" crossorigin />")
[void]$sb.AppendLine("  <link href=""https://fonts.googleapis.com/css2?family=Cinzel+Decorative:wght@700;900&family=Cinzel:wght@500;600;700;800;900&family=Playfair+Display:ital,wght@0,400;0,600;0,700;0,800;0,900;1,400;1,600;1,700&family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&display=swap"" rel=""stylesheet"" />")
[void]$sb.AppendLine("  <script src=""https://cdn.tailwindcss.com""></script>")
[void]$sb.AppendLine("  <script>")
[void]$sb.AppendLine("    tailwind.config = {")
[void]$sb.AppendLine("      theme: {")
[void]$sb.AppendLine("        extend: {")
[void]$sb.AppendLine("          colors: {")
[void]$sb.AppendLine("            royal: {")
[void]$sb.AppendLine("              navy: '#07142F',")
[void]$sb.AppendLine("              purple: '#1B0B36',")
[void]$sb.AppendLine("              burgundy: '#3A0B18',")
[void]$sb.AppendLine("              obsidian: '#050505',")
[void]$sb.AppendLine("              gold: '#C9A227',")
[void]$sb.AppendLine("              champagne: '#F1D78B',")
[void]$sb.AppendLine("              ivory: '#FFF8E7'")
[void]$sb.AppendLine("            }")
[void]$sb.AppendLine("          },")
[void]$sb.AppendLine("          fontFamily: {")
[void]$sb.AppendLine("            cinzel: ['""Cinzel""', 'serif'],")
[void]$sb.AppendLine("            'cinzel-decor': ['""Cinzel Decorative""', 'serif'],")
[void]$sb.AppendLine("            serif: ['""Playfair Display""', 'Georgia', 'serif'],")
[void]$sb.AppendLine("            sans: ['""Plus Jakarta Sans""', 'system-ui', 'sans-serif']")
[void]$sb.AppendLine("          }")
[void]$sb.AppendLine("        }")
[void]$sb.AppendLine("      }")
[void]$sb.AppendLine("    };")
[void]$sb.AppendLine("  </script>")
[void]$sb.AppendLine("  <script crossorigin src=""https://unpkg.com/react@18/umd/react.production.min.js""></script>")
[void]$sb.AppendLine("  <script crossorigin src=""https://unpkg.com/react-dom@18/umd/react-dom.production.min.js""></script>")
[void]$sb.AppendLine("  <script src=""https://unpkg.com/@babel/standalone/babel.min.js""></script>")
[void]$sb.AppendLine("  <script src=""https://cdn.jsdelivr.net/npm/canvas-confetti@1.6.0/dist/confetti.browser.min.js""></script>")
[void]$sb.AppendLine("  <style>")
[void]$sb.AppendLine($css)
[void]$sb.AppendLine("  </style>")
[void]$sb.AppendLine("</head>")
[void]$sb.AppendLine("<body class=""bg-[#050505] text-[#FFF8E7] selection:bg-[#C9A227] selection:text-[#050505]"">")
[void]$sb.AppendLine("  <div id=""root""></div>")
[void]$sb.AppendLine("  <script type=""text/javascript"">")
[void]$sb.AppendLine($data)
[void]$sb.AppendLine("  </script>")
[void]$sb.AppendLine("  <script type=""text/babel"">")
[void]$sb.AppendLine($app)
[void]$sb.AppendLine("  </script>")
[void]$sb.AppendLine("</body>")
[void]$sb.AppendLine("</html>")

[System.IO.File]::WriteAllText("c:\Users\ntkha\Documents\friends furnitures\index.html", $sb.ToString(), [System.Text.Encoding]::UTF8)
Write-Host "Self-contained index.html generated successfully."
